name: DefectDojo Report Upload Actions

description: Here we can upload the DefectDojo report to the DefectDojo server.

author: 'tharun13055'
inputs:
  DEFECTDOJO_TOKEN:
    description: 'DefectDojo API token'
    required: true
  DEFECTDOJO_URL:
    description: 'URL of the DefectDojo server'
    required: true
  FILE_PATH_WITH_FILE_NAME:
    description: 'Path to the file to be uploaded'
    required: true
  PRODUCT_NAME:
    description: 'Name of the product in DefectDojo'
    required: true
  SCAN_TYPE:
    description: 'Type of scan'
    required: true

runs:
  using: docker
  image: 'Dockerfile'

branding:
  icon: 'upload-cloud'
  color: 'orange'
