name: testing the actions

description: Here we can upload the DefectDojo report to the DefectDojo server.

on:
  push:
    branches:
      - test

jobs:
  defectdojo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: check the path
        run: |
          ls -l
          cd result 
          ls

      - name: DefectDojo Report Upload Actions
        uses: ./
        with:
          DEFECTDOJO_TOKEN: ${{ secrets.DEFECTDOJO_TOKEN }}
          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
          FILE_PATH_WITH_FILE_NAME: '/result/trivy.json'
          PRODUCT_NAME: 'test'
          SCAN_TYPE: 'Trivy Scan'